"""empty message

Revision ID: 018948bd2a52
Revises: 
Create Date: 2025-01-25 16:57:56.149558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "018948bd2a52"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bargainer_id", sa.Integer(), nullable=False),
        sa.Column("bargainee_id", sa.Integer(), nullable=False),
        sa.Column("give", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("take", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("barter")
    # ### end Alembic commands ###
