"""empty message

Revision ID: 2e93e3b73a93
Revises: c0db3e057d58
Create Date: 2025-01-26 16:26:54.446760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2e93e3b73a93"
down_revision: Union[str, None] = "c0db3e057d58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("barter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "give_done", sa.Boolean(), server_default=sa.text("0"), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "take_done", sa.Boolean(), server_default=sa.text("0"), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("barter", schema=None) as batch_op:
        batch_op.drop_column("take_done")
        batch_op.drop_column("give_done")

    # ### end Alembic commands ###
