"""empty message

Revision ID: c0db3e057d58
Revises: 018948bd2a52
Create Date: 2025-01-25 21:40:02.891625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c0db3e057d58"
down_revision: Union[str, None] = "018948bd2a52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bargainer", sa.Integer(), nullable=False),
        sa.Column("bargainee", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("associations")
    # ### end Alembic commands ###
